apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: d1
  name: d1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: d1
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: d1
    spec:
      containers:
      - image: xxxx:{VERSION}
        name: d1
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
